### ISSUE TITLE
Allow deleting maps

### ISSUE THREAD

**Issue by Pyredrid** [huderlem/porymap#288] opened 2020-08-25 23:19 UTC
Currently, only new maps can be created and added.  Being able to delete old/unused maps in the GUI would free up space and avoid clutter.  It'd also make the user's workflow smoother since right now deleting a map involves editing/deleting several files.

**Comment by huderlem** [comment] 2020-09-25 01:23
Duplicate of #19 .  I don't think we're ever going to do this.  Users who want to delete maps will be savy enough to do so by hand.  Making it easy via UI will just open pandora's box for people being confused why their builds are now failing due to C code referencing the deleted maps.

**Closed by huderlem** 2020-09-25 01:23 UTC
