### ISSUE TITLE
Alternate Layouts No editable

### ISSUE THREAD

**Issue by Fact-Smash** [huderlem/porymap#594] opened 2024-03-19 18:28 UTC
In the pokeemerald decomp, certain maps have alternate versions (my main example is Route 111 and its "Route111_NoMirageTower" layout). These versions don't appear as editable options in porymap meaning route 111 and similar areas can't change their size without major errors.

**Comment by GriffinRichards** [comment] 2024-03-19 18:52
Thanks! This is a duplicate of #182, and will be resolved in a future release by #515.

Here are two options for editing these layouts in current releases, using your example:
- Create a placeholder map for `Route111_NoMirageTower`. To do this, sort the map list by layout with the button in the top left, then right-click `Route111_NoMirageTower` and select `Add New Map with Layout`. Make your edits to this new map

-  Change the `layout` field in the `data/maps/Route111/map.json` file from `LAYOUT_ROUTE111` to `LAYOUT_ROUTE111_NO_MIRAGE_TOWER`, reload Porymap, make your edits to the `Route111` map, then revert the change to the `map.json` file.

**Closed by GriffinRichards** 2024-03-19 18:52 UTC
