### ISSUE TITLE
Crash when clicking on current map while loading a new one

### ISSUE THREAD

**Issue by lassellie** [huderlem/porymap#196] opened 2020-03-16 02:43 UTC
I've been having an issue where porymap will crash and close if it gets even slightly confused.  What I mean by this is that when I try to test a warp but then I click somewhere else, I run the risk of the software crashing.  It's happened a few times now, and has caused me to lose some progress before.

**Comment by GriffinRichards** [comment] 2020-04-29 16:52
This is on Windows correct? I've been unable to reproduce this on macOS

**Comment by huderlem** [comment] 2020-05-13 21:35
I can't seem to reproduce it on Windows.

**Comment by huderlem** [comment] 2020-05-22 00:23
Closing this issue as we can't reproduce it.  @lassellie  please let us know if you are able to recreate this issue in the future.

**Closed by huderlem** 2020-05-22 00:23 UTC
