### ISSUE TITLE
Event scripts dropping assignment during compile

### ISSUE THREAD

**Issue by danenders** [huderlem/porymap#418] opened 2022-03-11 20:06 UTC
When compiling after making changes to a map, events will randomly unassign their scripts and generate the following error:

`data/maps/NewMauville_Inside/events.inc: Assembler messages:
data/maps/NewMauville_Inside/events.inc:8: Error: Missing value for required parameter script' of macro object_event'
make:  [build/emerald/data/map_events.o] Error 1`

The script that is unassigned is not always the same, and does not always get dropped from an event that has been moved/newly created/or edited in any way. 

This has only occurred so far when viewing maps sorted by layout, but I haven't challenged this by making extensive changes on other maps to see if it occurs elsewhere. This round of edits have also been my most extensive.

Running version 4.5.0
OS: Mojave 10.14.6

**Comment by GriffinRichards** [comment] 2022-03-31 16:07
Duplicate of #380 

I'm still not sure what the conditions for this are. I imagine I don't make edits on the same scale as people actively working on larger projects, and as a result I haven't yet reproduced it personally.

**Closed** 2022-10-18 00:41 UTC
Labels: duplicate
