### ISSUE TITLE
Tileset editor duplicating metatiles

### ISSUE THREAD

**Issue by CharmQuarks** [huderlem/porymap#176] opened 2020-01-02 00:17 UTC
Metatiles 0x200 through 0x27F are duplicated directly below themselves, this duplication only happens once and after the second 0x27F the metatiles work normally again.

**Comment by huderlem** [comment] 2020-02-02 21:10
Closing, since I'm unable to reproduce this.  If you're able to provide a concrete set of steps to reproduce the issue, please reopen this Issue with that information.

**Closed by huderlem** 2020-02-02 21:10 UTC
