### ISSUE TITLE
Suggestion, mix border view utility with connections.

### ISSUE THREAD

**Issue by Meister-anon** [huderlem/porymap#369] opened 2021-06-26 19:12 UTC
In the map view, clicking the border box, allows us to see the map connections.

But we still have to go to the connection menu to be able to shift to the next map by clicking on
the connection.

Would be a good time-saver and work flow improvement, 
to be able move to the next map, just by clicking on the connection
from the map view when the border is being shown.

**Comment by BigBahss** [comment] 2021-06-27 02:51
Duplicate of #245

**Comment by BigBahss** [comment] 2021-06-27 05:52
I'm gonna move your comment to #245 and close this.

**Closed by BigBahss** 2021-06-27 05:52 UTC
