### ISSUE TITLE
Porymap should never crash when opening a project

### ISSUE THREAD

**Issue by kkamg10** [huderlem/porymap#177] opened 2020-01-13 20:26 UTC
I downloaded it and was very excited to use it. But when I opened it, I realized that the game simply closes when I try to open my pokeemerald, nothing happens, and then it closes. :(

**Comment by garakmon** [comment] 2020-01-13 22:25
More specificity would help with diagnosing the cause of your crashes. What edits have you made to your project? Do you have the all the commits listed under the "Breaking Changes" sections in the CHANGELOG.md?

**Comment by huderlem** [comment] 2020-02-02 21:12
Changing title, to capture a generic "don't crash ever upon startup".

**Comment by huderlem** [comment] 2020-02-02 21:13
We made improvements to this issue in the past, but it's still possible for segfaults etc. to cause porymap to crash due to its assumptions about how projects are structured.

**Comment by huderlem** [comment] 2020-02-12 17:28
This should be fixed with commits: 79c74b8814d640e8550a178cde29e28c024b00f8 ... 2df0ac7d16d71b5145b35988be7e1ff2d2ce39a6

**Closed by huderlem** 2020-02-12 17:28 UTC
